#use_frameworks!

platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'LTEmptyView_Example' do
  pod 'LTEmptyView', :path => '../'

  target 'LTEmptyView_Tests' do
    inherit! :search_paths

    
  end
end
